name: "Upload to Sharepoint"
description: "Upload files to Sharepoint"
author: "Experience Catalyst"
inputs:
  aemy_callbacks:
    description: "The AEMY callback information."
    required: true
  aemy_context:
    description: "The AEMY context as a string."
    required: true
  sharepoint_client_id:
    description: "The SharePoint client id."
    required: true
  sharepoint_tenant_id:
    description: "The SharePoint tenant id."
    required: true
  sharepoint_client_secret:
    description: "The SharePoint client secret."
    required: true
  upload_target:
    description: "The SharePoint site URL."
    required: true
  upload_source:
    description: "The folder containing the files to upload."
    required: true
outputs:
  result:
    description: "The results of the upload as a JSON string with status and message properties."
runs:
  using: "composite"
  steps:
    - name: "Upload the files"
      run: |
        bash .github/actions/upload-sharepoint/upload-to-sharepoint.sh "${{ inputs.upload_source }}" "${{ inputs.upload_target }}" \
          "${{ inputs.sharepoint_tenant_id }}" "${{ inputs.sharepoint_client_id }}" "${{ inputs.sharepoint_client_secret }}" \
          "${{ inputs.aemy_callbacks }}" "${{ inputs.aemy_context }}"
      shell: bash
